apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  lables:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: nginx
      command: ['sh','-c','echo The app is running! && sleep 3600']
    initContainers:
      - name: init-myservice
        image: redis
        command: ['sh','-c','']